# Generated by Django 5.2.3 on 2025-07-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('sale', 'Sale'), ('out_of_stock', 'Out of Stock')], default='new', max_length=20),
        ),
    ]
