# Generated by Django 5.2.4 on 2025-07-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('sale', 'Sale'), ('out_of_stock', 'Out of Stock'), ('regular', 'Regular')], default='new', max_length=20),
        ),
    ]
